"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
MA = HERE / "match_accuracy" / "results"
CR = HERE / "candidate_recall" / "results"
US = HERE / "unmatched_split" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _md(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    ma = _read(MA / "results.json")
    cr = _read(CR / "results.json")
    us = _read(US / "results.json")
    ma_md = _md(MA / "results.md")
    cr_md = _md(CR / "results.md")
    us_md = _md(US / "results.md")
    ma_table = "\n".join(line for line in ma_md.splitlines() if line.startswith("|"))
    cr_table = "\n".join(line for line in cr_md.splitlines() if line.startswith("|"))
    us_table = "\n".join(line for line in us_md.splitlines() if line.startswith("|"))
    cost = "\n".join(
        [
            f"- Probe set: {ma['n_pairs']} designed pairing tasks, committed JSON.",
            f"- Adjudication set: {us['n']} unmatched trials, committed labels.",
            "- Live ClinicalTrials.gov / PubMed pull: unmeasured.",
            "- Human curator time per unmatched adjudication: unmeasured.",
            "- API RTT: unmeasured (no live calls).",
            "- Matcher CPU on 200 pairs: unmeasured as a separate timer "
            "(runs inside match_accuracy; wall time is dominated by process startup).",
        ]
    )
    filled = (
        template.replace("{{MA_N}}", str(ma["n_pairs"]))
        .replace("{{MA_PRECISION}}", f"{ma['precision']:.3f}")
        .replace("{{MA_RECALL}}", f"{ma['recall']:.3f}")
        .replace("{{MA_F1}}", f"{ma['f1']:.3f}")
        .replace("{{MA_DECISION}}", str(ma["decision"]))
        .replace("{{MA_TABLE}}", ma_table)
        .replace("{{CR_DECISION}}", str(cr["decision"]))
        .replace("{{CR_TABLE}}", cr_table)
        .replace("{{US_N}}", str(us["n"]))
        .replace("{{US_MISSED_FRAC}}", f"{us['reported_but_unmatched_fraction']:.3f}")
        .replace("{{US_GENUINE_FRAC}}", f"{us['genuinely_unreported_fraction']:.3f}")
        .replace("{{US_DECISION}}", str(us["decision"]))
        .replace("{{US_TABLE}}", us_table)
        .replace("{{COST_MODEL}}", cost)
    )
    return filled


def render_eval() -> str:
    ma = _md(MA / "results.md")
    cr = _md(CR / "results.md")
    us = _md(US / "results.md")
    ma_json = _read(MA / "results.json")
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. "
        "Live ClinicalTrials.gov / PubMed hold-out numbers do not exist yet. "
        "The MATCH precision and recall below decide whether a headline "
        "non-reporting rate would be defensible.\n\n"
        f"MATCH precision: **{ma_json['precision']:.3f}**. "
        f"MATCH recall: **{ma_json['recall']:.3f}**. "
        f"Headline defensible: **{'yes' if ma_json['headline_defensible'] else 'no'}**.\n\n"
        f"{ma}\n\n{cr}\n\n{us}\n"
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    readme_path = ROOT / "README.md"
    if not readme_path.exists():
        return
    ma = _read(MA / "results.json")
    cr = _read(CR / "results.json")
    us = _read(US / "results.json")
    combined = cr["strategies"]["combined"]["recall"]
    body = (
        "| Measurement | Result | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Matcher MATCH precision | {ma['precision']:.3f} | {ma['n_pairs']} | "
        f"Floor {ma['precision_floor']:.2f} |\n"
        f"| Matcher MATCH recall | {ma['recall']:.3f} | {ma['n_pairs']} | "
        f"Floor {ma['recall_floor']:.2f} |\n"
        f"| Combined candidate-generation recall | {combined:.3f} | "
        f"{cr['n_positive_trials']} | Same 200 |\n"
        f"| Unmatched that are reported-but-unmatched | "
        f"{us['reported_but_unmatched_fraction']:.3f} | {us['n']} | "
        "Largest error source |\n"
        "| Live CT.gov / PubMed sponsor ranking | Phase 3 | — | Not pulled |\n\n"
        f"{ma['decision']}"
    )
    text = _replace_block(
        readme_path.read_text(encoding="utf-8"),
        "<!-- EVAL_TABLE_BEGIN -->",
        "<!-- EVAL_TABLE_END -->",
        body,
    )
    readme_path.write_text(text, encoding="utf-8")


def main() -> None:
    memo = render_memo()
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(memo, encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    patch_readme()
    print("wrote docs/phase-0/research-memo.md, docs/EVALUATION.md, README results block")


if __name__ == "__main__":
    main()
